### ISSUE TITLE
Add finding primes and prime factors in cpp

### ISSUE THREAD

**Issue by shashank1529** [imhardikdesai/DSA-Algorithms#13]
@imhardikdesai request you to assign this issue to me under hactoberfest label.

**Comment by iamrishabhjoshi** [comment]
@imhardikdesai request you to assign this issue to me under hactoberfest label.

**Comment by imhardikdesai** [comment]
You have to create pull request of that changes. You don't have to create an issue.
I will assigned you `hacktoberfest` label in pull request
