### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by Anirudh3167** [imhardikdesai/DSA-Algorithms#5]
Hi @imhardikdesai ,

I would like to add some basic algorithm concepts like linear search and binary search in python and c languages.

Kindly assign this to me

**Comment by imhardikdesai** [comment]
Go I assigned you

**Comment by Sscuber03** [comment]
I also want to add the basics of dsa concepts in c, like for linked list, doubl linked list etc. Can this be assigned to me also? or another issue needs to be created @imhardikdesai ?

**Comment by imhardikdesai** [comment]
You all have to add algorithm code file in specific folder and open pull request.
