### ISSUE TITLE
want to add stack operation 

### ISSUE THREAD

**Issue by ErMapsh** [imhardikdesai/DSA-Algorithms#96]

**Comment by Kirti36** [comment]
pls assign this to me...

**Comment by arunava2018** [comment]
I am well known to stack DS ! Please assign me this and help me to complete my 1st contribution in Hacktoberfest 2k22

**Comment by hemanthhhhhh** [comment]
I would like to add stack operation and I am very proficient in DSA (5 star coder). Please assign this project to me

**Comment by imhardikdesai** [comment]
I assigned you all
